version: "3.4"

services:
  postgres-server:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "5433:5432"
    volumes:
      # - docker-volume:/var/lib/postgresql/data
      - E:\PostgresDocker\Docker-Compose\PostgreSQL
    networks:
      - postgres-compose-network
    restart: unless-stopped

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "udanjo_hyuuga@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    depends_on:
      - postgres-server
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge

volumes:
  docker-volume:
    driver: local
